package exception.throws_;

public class MainClass {

	public static void main(String[] args) {
		
		try {
			ThrowsEx02 t = new ThrowsEx02();
		} catch (Exception e) {
			System.out.println("예외가 발생했습니다.");
		}
		
		
		
	}

}
